"""Type definitions for Google API services."""

from typing import Protocol, Any, Dict, List

class DriveFilesResource(Protocol):
    """Protocol for Google Drive files resource methods."""
    def list(self, **kwargs: Any) -> Dict[str, Any]: ...
    def get(self, fileId: str, **kwargs: Any) -> Dict[str, Any]: ...
    def get_media(self, fileId: str) -> Any: ...

class DriveService(Protocol):
    """Protocol for Google Drive service."""
    def files(self) -> DriveFilesResource: ...

class SheetsValuesResource(Protocol):
    """Protocol for Google Sheets values resource methods."""
    def get(self, spreadsheetId: str, range: str, **kwargs: Any) -> Dict[str, Any]: ...
    def batchUpdate(self, spreadsheetId: str, body: Dict[str, Any]) -> Dict[str, Any]: ...

class SheetsSpreadsheetsResource(Protocol):
    """Protocol for Google Sheets spreadsheets resource methods."""
    def get(self, spreadsheetId: str, **kwargs: Any) -> Dict[str, Any]: ...
    def values(self) -> SheetsValuesResource: ...

class SheetsService(Protocol):
    """Protocol for Google Sheets service."""
    def spreadsheets(self) -> SheetsSpreadsheetsResource: ...

class UserinfoResource(Protocol):
    """Protocol for Google OAuth2 userinfo resource methods."""
    def get(self) -> Dict[str, Any]: ...

class UserinfoService(Protocol):
    """Protocol for Google OAuth2 userinfo service."""
    def userinfo(self) -> UserinfoResource: ... 